services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dbtarefa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ---- NOVO BLOCO ADICIONADO AQUI ----
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dbtarefa"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: dbtarefa
      DB_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: